import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { ActivityIndicator, Platform, Pressable, ScrollView, StyleSheet, View, useWindowDimensions } from './ui';
import { router, useLocalSearchParams } from './navigation';
import { Ionicons } from './ui';
import { SafeAreaView } from './ui';
import { Bouton, Champ, Etiquette, Logotype, Texte } from './ui';
import { ReglagesAdmin } from './Reglages';
import { api } from './api';

import { confirmer } from './navigation';
import { euros } from '../src/lib/argent';
import { colors } from './ui';
import type { AdminOverview } from '../src/types/admin';

const sections=[['overview','Vue d’ensemble','grid-outline'],['annonces','Annonces','pricetags-outline'],['membres','Membres','people-outline'],['commandes','Commandes','bag-handle-outline'],['livraisons','Livraisons','cube-outline'],['litiges','Litiges & support','chatbubbles-outline'],['moderation','Signalements','flag-outline'],['boosts','Boosts','flash-outline'],['emails','E-mails','mail-outline'],['exports','Exports','download-outline'],['reglages','Réglages','options-outline'],['journal','Journal','list-outline']] as const;
type Section=typeof sections[number][0];
const labels:Record<string,string>={paiement_en_attente:'Paiement en attente',sequestre:'Payée · à préparer',etiquette_emise:'Préparée',expedie:'Expédiée',livre:'Livrée',litige:'En litige',finalisee:'Terminée',remboursement_en_cours:'Remboursement en cours',remboursee:'Remboursée',annulee:'Annulée',en_ligne:'En ligne',reservee:'Réservée',vendue:'Vendue',masquee:'Masquée',supprimee:'Archivée',active:'Actif',pending:'En attente',expired:'Terminé',refunded:'Remboursé',refund_pending:'Remboursement en cours',canceled:'Expiré',accepted:'Accepté par Brevo',failed:'Échec',actif:'Actif',averti:'Averti',suspendu:'Suspendu',banni:'Banni',ouvert:'Ouvert',en_examen:'En examen',resolu:'Résolu',clos:'Clos'};
function Badge({value}:{value:string}) {return <Etiquette libelle={labels[value] || value} ton={['failed','banni','litige'].includes(value)?'danger':['active','actif','finalisee','accepted','resolu'].includes(value)?'succes':'neutre'}/>;}
function Card({children}:{children:ReactNode}) {return <View style={styles.card}>{children}</View>;}
function date(value:string) {return new Date(value).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'});}
function exportCsv(name:string,rows:(string|number)[][]) {
  if(Platform.OS!=='web')throw new Error('Ouvre le dashboard dans un navigateur pour télécharger les exports.');
  const escape=(v:string|number)=>'"'+String(v).replace(/^[=+\-@\t\r]/,"'$&").replaceAll('"','""')+'"';
  const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(escape).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));
  const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function Dashboard({logout}:{logout:()=>void}) {
  const {section:initial}=useLocalSearchParams<{section?:string}>();
  const [section,setSection]=useState<Section>(sections.some(s=>s[0]===initial)?initial as Section:'overview');
  const [data,setData]=useState<AdminOverview>();const [error,setError]=useState('');
  const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [reason,setReason]=useState('');
  const [support,setSupport]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);const revision=useRef(0);
  const {width}=useWindowDimensions();const wide=width>=1024;
  const refresh=useCallback(async()=>{const current=++revision.current;try{const value=await api<AdminOverview>('/admin/overview');if(current===revision.current){setData(value);setError('');}}catch(e){if(current===revision.current)setError((e as Error).message);}},[]);
  useEffect(()=>{void refresh();const t=setInterval(()=>{if(!lock.current)void refresh();},15000);return()=>clearInterval(t);},[refresh]);
  const perform=async(body:unknown)=>{if(lock.current)throw new Error('Une action est déjà en cours.');lock.current=true;revision.current++;setBusy(true);try{const value=await api<AdminOverview>('/admin/action',body);setData(value);setError('');setReason('');}catch(e){setError((e as Error).message);throw e;}finally{lock.current=false;setBusy(false);}};
  const sensitive=async(body:Record<string,unknown>,title:string)=>{if(reason.trim().length<10)throw new Error('Indique un motif d’au moins 10 caractères dans le champ au-dessus de la liste.');if(await confirmer(title,reason,'Confirmer',true))await perform({...body,reason});};
  const go=(next:Section)=>{history.replaceState(null,'',`#${next}`);setSection(next);setQuery('');setFilter('all');setReason('');};
  const title=sections.find(s=>s[0]===section)![1];
  const s=data?.state;const match=(...values:unknown[])=>values.join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase());
  const user=(id:string)=>s?.utilisateurs.find(u=>u.id===id)?.pseudo || id;
  const article=(id:string)=>s?.annonces.find(a=>a.id===id)?.titre || 'Article retiré';
  const filtered=(status:string)=>filter==='all'||status===filter;
  const action=(title:string,onPress:()=>unknown,danger=false)=><Bouton titre={title} taille="sm" ton={danger?'danger':'contour'} desactive={busy} onPress={onPress}/>;
  const empty=<Texte variante="corpsDoux">Aucun résultat pour cette sélection.</Texte>;
  const reasonInput=['annonces','membres','commandes','livraisons','litiges','boosts'].includes(section);
  const statuses=section==='annonces'?['en_ligne','reservee','vendue','masquee','supprimee']:['commandes','livraisons'].includes(section)?['paiement_en_attente','sequestre','etiquette_emise','expedie','livre','litige','finalisee','remboursee']:section==='membres'?['actif','averti','suspendu','banni']:section==='boosts'?['active','pending','expired','refunded']:section==='emails'?['accepted','pending','failed']:section==='litiges'?['ouvert','en_examen','resolu']:[];
  const commandes=s?.commandes.filter(c=>(section!=='livraisons'||c.mode==='colissimo')&&filtered(c.statut)&&match(c.reference,article(c.annonceId),user(c.acheteurId),user(c.vendeurId))) || [];
  const nav=<>{sections.map(([id,label,icon])=><Pressable key={id} accessibilityRole="button" accessibilityState={{selected:section===id}} onPress={()=>go(id)} style={[styles.navItem,section===id&&styles.navActive]}><Ionicons name={icon} size={19} color={section===id?colors.encre:'#D4E1DC'}/><Texte couleur={section===id?colors.encre:'#D4E1DC'} style={{fontSize:14}}>{label}</Texte></Pressable>)}</>;
  return <SafeAreaView style={styles.base}>
    {wide && <View style={styles.sidebar}><Logotype hauteur={36} sombre/><Texte variante="micro" couleur="#ABBFB5">L’ESPACE DE PILOTAGE</Texte><ScrollView contentContainerStyle={{gap:4,paddingTop:20,paddingBottom:20}}>{nav}</ScrollView><Texte variante="petit" couleur="#D4E1DC">La Réunion · 974</Texte><Bouton titre="Se déconnecter" ton="contourClair" taille="sm" onPress={logout}/><Bouton titre="Voir l’application" ton="contourClair" taille="sm" onPress={()=>router.push('/(tabs)')}/></View>}
    <View style={{flex:1,minWidth:0}}>
      <View style={styles.header}><View style={{flex:1,gap:4}}><Texte variante="micro">LIKED / ADMINISTRATION</Texte><Texte variante="soustitre">{title}</Texte></View><Etiquette libelle={data?.services.stripe==='live'?'PRODUCTION':'MODE TEST'} ton="action"/>{action('Actualiser',refresh)}{!wide&&action('Déconnexion',logout)}</View>
      {!wide && <ScrollView horizontal style={{flexGrow:0,backgroundColor:colors.encre}} contentContainerStyle={{padding:12,gap:8}}>{nav}</ScrollView>}
      <ScrollView contentContainerStyle={{padding:wide?32:16,gap:20,paddingBottom:70,maxWidth:1500,width:'100%',alignSelf:'center'}} keyboardShouldPersistTaps="handled">
        {error && <Card><Texte couleur={colors.danger} accessibilityRole="alert">{error}</Texte>{action('Réessayer',refresh)}</Card>}
        {!data ? <ActivityIndicator color={colors.corail}/> : <>
          <View style={styles.row}><Texte variante="petit">Bonjour {user(s!.sessionId!)}. Voici ce qui se passe sur Liked.</Texte><Texte variante="micro">Actualisé à {new Date(data.updatedAt).toLocaleTimeString('fr-FR')}</Texte></View>
          {!['overview','reglages','exports'].includes(section)&&<Champ accessibilityLabel="Rechercher dans cette rubrique" placeholder="Rechercher un article, un membre, une référence…" value={query} onChangeText={setQuery}/>}
          {statuses.length>0&&<View style={styles.actions}>{['all',...statuses].map(v=><Bouton key={v} taille="sm" ton={filter===v?'encre':'discret'} titre={v==='all'?'Tous':labels[v]||v} onPress={()=>setFilter(v)}/>)}</View>}
          {reasonInput&&<Champ label="Motif de l’action (modération ou remboursement)" placeholder="Explique la décision, au moins 10 caractères" value={reason} onChangeText={setReason}/>}
          {section==='overview'&&<>
            <View style={styles.hero}><View style={{flex:1,gap:10}}><Texte variante="titre" couleur={colors.blanc}>Un œil sur toute{'\n'}ta communauté.</Texte><Texte couleur="#CFDDD5">Les bons indicateurs. Les actions qui comptent.</Texte></View><Ionicons name="leaf-outline" size={64} color="#AEC7AE"/></View>
            <View style={styles.metrics}>{[
              ['Membres',String(s!.utilisateurs.length),'membres'],['Annonces en ligne',String(s!.annonces.filter(a=>a.statut==='en_ligne').length),'annonces'],
              ['Commandes payées',String(s!.commandes.filter(c=>!['paiement_en_attente','annulee','remboursee'].includes(c.statut)).length),'commandes'],
              ['Volume payé net',euros(s!.commandes.filter(c=>!['paiement_en_attente','annulee','remboursee'].includes(c.statut)).reduce((n,c)=>n+c.totalCents,0)),'commandes'],
              ['Revenus sur ventes terminées',euros(s!.commandes.filter(c=>c.statut==='finalisee').reduce((n,c)=>n+c.fraisProtectionCents+c.margePortCents,0)),'exports'],
              ['Boosts payés nets',euros(data.boosts.filter(b=>['active','expired','refund_pending'].includes(b.status)).reduce((n,b)=>n+b.amount,0)),'boosts'],
            ].map(([label,value,target])=><Pressable key={label} accessibilityRole="button" onPress={()=>go(target as Section)} style={styles.metric}><Texte variante="micro">{label}</Texte><Texte style={{fontSize:30,fontWeight:'600',color:colors.encre}}>{value}</Texte><Texte variante="petit">Voir le détail ↗</Texte></Pressable>)}</View>
            <View style={styles.row}><View style={{flex:1,minWidth:250}}><Card><Texte variante="section">À traiter</Texte>{action(`${s!.signalements.filter(x=>!x.traite).length} signalement(s)`,()=>go('moderation'))}{action(`${s!.litiges.filter(x=>['ouvert','en_examen'].includes(x.statut)).length} litige(s) ouvert(s)`,()=>go('litiges'))}{action(`${data.emails.filter(x=>x.status==='failed').length} e-mail(s) en échec`,()=>go('emails'))}</Card></View><View style={{flex:1,minWidth:250}}><Card><Texte variante="section">Services</Texte><Texte>Stripe : {data.services.stripe==='live'?'paiements réels configurés':data.services.stripe==='test'?'paiements fictifs configurés':'à configurer'}</Texte><Texte>Brevo : {data.services.brevo?'envoi configuré':'à configurer'}</Texte><Texte>Colissimo : {data.reglages.colissimoActif?'activé · simulation':'désactivé'}</Texte>{action('Gérer les options',()=>go('reglages'))}</Card></View></View>
            <Card><Texte variante="section">Dernières commandes</Texte>{s!.commandes.slice(0,5).map(c=><View key={c.id} style={styles.row}><Texte>{c.reference} · {article(c.annonceId)}</Texte><Badge value={c.statut}/><Texte>{euros(c.totalCents)}</Texte></View>)}{!s!.commandes.length&&<Texte>Les premières commandes apparaîtront ici après un essai.</Texte>}</Card>
          </>}
          {section==='annonces'&&<>{s!.annonces.filter(a=>filtered(a.statut)&&match(a.titre,a.id,user(a.vendeurId))).map(a=><Card key={a.id}><View style={styles.row}><View style={{flex:1,gap:4}}><Texte variante="section">{a.titre}</Texte><Texte variante="petit">{user(a.vendeurId)} · {a.marque} · {a.taille}</Texte></View><Texte variante="prix">{euros(a.prixCents)}</Texte><Badge value={a.statut}/></View><View style={styles.actions}>{action('Voir l’annonce',()=>router.push(`/annonce/${a.id}`))}{!['reservee','vendue'].includes(a.statut)&&<>{action(a.statut==='en_ligne'?'Masquer':'Rétablir',()=>sensitive({action:'moderate',id:a.id,value:a.statut==='en_ligne'?'masquer':'retablir'},`Modifier « ${a.titre} »`))}{a.statut!=='supprimee'&&action('Archiver',()=>sensitive({action:'moderate',id:a.id,value:'supprimer'},`Archiver « ${a.titre} »`),true)}</>}</View></Card>)}{!s!.annonces.some(a=>filtered(a.statut)&&match(a.titre,a.id,user(a.vendeurId)))&&empty}</>}
          {section==='membres'&&<>{s!.utilisateurs.filter(u=>filtered(u.statut)&&match(u.pseudo,u.email,u.commune)).map(u=><Card key={u.id}><View style={styles.row}><View style={{flex:1,gap:5}}><Texte variante="section">{u.pseudo}{u.role==='admin'?' · administrateur':''}</Texte><Texte>{u.email}</Texte><Texte variante="petit">{u.commune} · {u.nombreVentes} vente(s) · compte vendeur : {data.accounts.includes(u.id)?u.kyc:'non connecté'}</Texte></View><Badge value={u.statut}/></View><View style={styles.actions}>{u.role!=='admin'&&(['actif','averti','suspendu','banni'] as const).filter(v=>v!==u.statut).map(v=><Bouton key={v} titre={{actif:'Réactiver',averti:'Avertir',suspendu:'Suspendre',banni:'Bannir'}[v]} taille="sm" ton={v==='banni'?'danger':'contour'} desactive={busy} onPress={()=>sensitive({action:'sanction',id:u.id,value:v},`${labels[v]} · ${u.pseudo}`)}/>)}{data.accounts.includes(u.id)&&action('Synchroniser Stripe',()=>perform({action:'stripe_status',id:u.id}))}</View></Card>)}{!s!.utilisateurs.some(u=>filtered(u.statut)&&match(u.pseudo,u.email,u.commune))&&empty}</>}
          {['commandes','livraisons'].includes(section)&&<>{section==='livraisons'&&<Card><Texte variante="section">Colissimo {data.reglages.colissimoActif?'activé · mode test':'désactivé'}</Texte><Texte>Les étapes ci-dessous simulent le transport. Elles ne créent aucune étiquette utilisable pour expédier un vrai colis.</Texte>{action('Ouvrir les réglages',()=>go('reglages'))}</Card>}{commandes.map(c=><Card key={c.id}><View style={styles.row}><View style={{flex:1,gap:4}}><Texte variante="section">{c.reference} · {article(c.annonceId)}</Texte><Texte variante="petit">{date(c.creeeLe)} · {user(c.vendeurId)} → {user(c.acheteurId)}</Texte></View><Badge value={c.statut}/><Texte variante="prix">{euros(c.totalCents)}</Texte></View><Texte variante="petit">Article {euros(c.prixArticleCents)} · protection {euros(c.fraisProtectionCents)} · port {euros(c.fraisPortCents)} · {c.mode==='colissimo'?'Colissimo de test':'Remise en main propre'}</Texte>{c.adresseLivraison&&<Texte variante="petit">Livraison : {c.adresseLivraison.nomComplet}, {c.adresseLivraison.ligne1}, {c.adresseLivraison.codePostal} {c.adresseLivraison.ville}</Texte>}{c.numeroSuivi&&<Texte>Suivi : {c.numeroSuivi}</Texte>}<Texte variante="petit">Dernière étape : {c.journal.at(-1)?.libelle}</Texte><View style={styles.actions}>{!c.litigeId&&['sequestre','etiquette_emise','remboursement_en_cours'].includes(c.statut)&&action('Rembourser intégralement',()=>sensitive({action:'refund',id:c.id},`Rembourser ${euros(c.totalCents)} · ${c.reference}`),true)}{c.mode==='colissimo'&&!c.litigeId&&(['sequestre','etiquette_emise','expedie'].includes(c.statut))&&action({sequestre:'Simuler la préparation',etiquette_emise:'Simuler l’expédition',expedie:'Simuler la livraison'}[c.statut as 'sequestre']||'Simuler',async()=>{if(await confirmer('Transport de test',`${c.reference} : avancer à l’étape suivante ?`,'Confirmer'))await perform({action:'shipping',id:c.id,value:{sequestre:'label',etiquette_emise:'ship',expedie:'deliver'}[c.statut as 'sequestre']});})}{c.litigeId&&action('Gérer le litige',()=>go('litiges'))}</View></Card>)}{!commandes.length&&empty}</>}
          {section==='litiges'&&<>{s!.litiges.filter(l=>filtered(l.statut)&&match(l.id,l.motif,l.description)).map(l=><Card key={l.id}><View style={styles.row}><Texte variante="section">{s!.commandes.find(c=>c.id===l.commandeId)?.reference} · {l.motif.replaceAll('_',' ')}</Texte><Badge value={l.statut}/></View><Texte>{l.description}</Texte>{l.photos.map((url,i)=>action(`Ouvrir la pièce ${i+1}`,()=>{if(Platform.OS==='web')window.open(url,'_blank','noopener,noreferrer');}))}{l.messages.map(m=><View key={m.id} style={styles.message}><Texte variante="micro">{m.role==='support'?'Support':user(m.auteurId)} · {date(m.le)}</Texte><Texte>{m.texte}</Texte></View>)}{l.decisionMotivee&&<Texte>Décision : {l.decisionMotivee}</Texte>}{['ouvert','en_examen'].includes(l.statut)&&<><Champ label="Réponse au litige" value={support} onChangeText={setSupport} multiline/><View style={styles.actions}>{action('Répondre',async()=>{await perform({action:'support',id:l.id,text:support});setSupport('');})}{action('Remboursement intégral',()=>sensitive({action:'dispute',id:l.id,value:'remboursement_total'},'Rembourser intégralement ce litige'),true)}{action('Verser au vendeur',()=>sensitive({action:'dispute',id:l.id,value:'versement_vendeur'},'Clore le litige et verser les fonds au vendeur'))}</View><Texte variante="petit">Un remboursement en cours reste ouvert jusqu’à sa confirmation par Stripe.</Texte></>}</Card>)}{!s!.litiges.some(l=>filtered(l.statut)&&match(l.id,l.motif,l.description))&&empty}</>}
          {section==='moderation'&&<>{s!.signalements.filter(r=>match(r.motif,r.cibleId,user(r.auteurId))).map(r=><Card key={r.id}><View style={styles.row}><Texte variante="section">{r.type} · {r.motif}</Texte><Etiquette libelle={r.traite?'Traité':'À traiter'} ton={r.traite?'succes':'alerte'}/></View><Texte>{r.detail || 'Aucun détail supplémentaire.'}</Texte>{r.type==='message'&&<Texte>Message signalé : {s!.messages.find(m=>m.id===r.cibleId)?.texte||'Message indisponible'}</Texte>}<Texte variante="petit">Cible : {r.cibleId} · par {user(r.auteurId)}</Texte><View style={styles.actions}>{action(r.type==='annonce'?'Gérer les annonces':'Gérer les membres',()=>go(r.type==='annonce'?'annonces':'membres'))}{!r.traite&&action('Marquer traité',()=>perform({action:'report',id:r.id}))}</View></Card>)}{!s!.signalements.length&&empty}</>}
          {section==='boosts'&&<><Card><Texte variante="section">Forfaits actuels</Texte><Texte>3 jours : {euros(data.reglages.boost3Cents)} · 7 jours : {euros(data.reglages.boost7Cents)}</Texte>{action('Modifier les tarifs',()=>go('reglages'))}</Card>{data.boosts.filter(b=>filtered(b.status)&&match(b.id,article(b.listing_id),user(b.user_id))).map(b=><Card key={b.id}><View style={styles.row}><Texte variante="section">{article(b.listing_id)}</Texte><Badge value={b.status}/></View><Texte>{user(b.user_id)} · {b.days} jours · {euros(b.amount)}</Texte>{b.ends_at&&<Texte variante="petit">Fin : {date(b.ends_at)}</Texte>}{['active','expired','refund_pending'].includes(b.status)&&action('Rembourser le boost',()=>sensitive({action:'boost_refund',id:b.id},`Rembourser ce boost de ${euros(b.amount)}`),true)}</Card>)}{!data.boosts.length&&empty}</>}
          {section==='emails'&&<><Texte variante="petit">Les 200 derniers e-mails transactionnels. « Accepté par Brevo » confirme l’envoi au prestataire, pas la réception en boîte principale. Les codes de connexion ne sont pas affichés.</Texte>{data.emails.filter(e=>filtered(e.status)&&match(e.subject,e.to)).map(e=><Card key={e.id}><View style={styles.row}><Texte variante="section">{e.subject}</Texte><Badge value={e.status}/></View><Texte>{e.to}</Texte><Texte variante="petit">{e.attempts} tentative(s)</Texte>{e.status==='failed'&&action('Réessayer l’envoi',()=>perform({action:'email_retry',id:e.id}))}</Card>)}{!data.emails.length&&empty}</>}
          {section==='exports'&&<Card><Texte variante="soustitre">Tes données, à portée de main.</Texte><Texte>Télécharge les données actuelles pour ton suivi comptable et opérationnel. Les montants sont exprimés en euros.</Texte>{action('Exporter les commandes',()=>exportCsv('liked-commandes.csv',[['Référence','Date','Statut','Acheteur','Vendeur','Article EUR','Protection EUR','Port EUR','Total EUR'],...s!.commandes.map(c=>[c.reference,c.creeeLe,c.statut,user(c.acheteurId),user(c.vendeurId),c.prixArticleCents/100,c.fraisProtectionCents/100,c.fraisPortCents/100,c.totalCents/100])]))}{action('Exporter le récapitulatif vendeurs',()=>exportCsv('liked-vendeurs.csv',[['Membre','Email','Année','Ventes finalisées','Montant EUR'],...s!.utilisateurs.map(u=>[u.pseudo,u.email,u.dac7.anneeReference,u.dac7.nombreTransactionsAnnuel,u.dac7.montantAnnuelCents/100])]))}{action('Exporter le journal',()=>exportCsv('liked-journal.csv',[['Date','Administrateur','Action','Cible','Motif'],...s!.journalAdmin.map(j=>[j.le,user(j.adminId),j.action,j.cible,j.detail||''])]))}<Texte variante="petit">Le récapitulatif vendeurs est un export de gestion ; il ne constitue pas un dépôt fiscal DAC7.</Texte></Card>}
          {section==='reglages'&&<Card><ReglagesAdmin data={data} save={perform}/></Card>}
          {section==='journal'&&<>{[...s!.journalAdmin].sort((a,b)=>b.le.localeCompare(a.le)).filter(j=>match(j.action,j.cible,j.detail,user(j.adminId))).map(j=><Card key={j.id}><Texte variante="section">{j.action}</Texte><Texte>{j.detail||j.cible}</Texte><Texte variante="petit">{user(j.adminId)} · {date(j.le)} · {j.cible}</Texte></Card>)}{!s!.journalAdmin.length&&empty}</>}
        </>}
      </ScrollView>
    </View>
  </SafeAreaView>;
}
const styles=StyleSheet.create({base:{flex:1,flexDirection:'row',backgroundColor:'#F3F5F0'},sidebar:{width:245,backgroundColor:colors.encre,padding:24,gap:16},navItem:{flexDirection:'row',alignItems:'center',gap:11,padding:13,borderRadius:12},navActive:{backgroundColor:'#DCE9D8'},header:{padding:22,backgroundColor:colors.blanc,borderBottomWidth:1,borderColor:'#E1E7DF',flexDirection:'row',alignItems:'center',gap:12,flexWrap:'wrap'},card:{backgroundColor:colors.blanc,borderWidth:1,borderColor:'#E1E7DF',borderRadius:20,padding:22,gap:14},hero:{backgroundColor:colors.encre,padding:30,borderRadius:24,flexDirection:'row',alignItems:'center',gap:20},row:{flexDirection:'row',alignItems:'center',gap:14,flexWrap:'wrap',justifyContent:'space-between'},actions:{flexDirection:'row',gap:10,flexWrap:'wrap'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:16},metric:{minWidth:220,flexGrow:1,flexBasis:'30%',gap:14,padding:24,backgroundColor:colors.blanc,borderWidth:1,borderColor:'#E1E7DF',borderRadius:20},message:{backgroundColor:'#F3F5F0',padding:14,borderRadius:12,gap:6}});
