import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
export const colors={encre:'#0B3B3C',corail:'#F27961',blanc:'#FFFFFF',encre15:'rgba(11,59,60,.15)',danger:'#A93131',succes:'#277252'};
type Style=CSSProperties | (CSSProperties|undefined|false)[];
const flatten=(style?:Style):CSSProperties=>Array.isArray(style)?Object.assign({},...style.filter(Boolean)):style||{};
interface Box {children?:ReactNode;style?:Style;accessibilityRole?:string;accessibilityLabel?:string;}
export function View({children,style,accessibilityRole,accessibilityLabel}:Box){return <div role={accessibilityRole} aria-label={accessibilityLabel} style={{display:'flex',flexDirection:'column',minWidth:0,...flatten(style)}}>{children}</div>;}
export const SafeAreaView=View;
export function ScrollView({children,style,contentContainerStyle,horizontal}:Box&{contentContainerStyle?:Style;horizontal?:boolean;keyboardShouldPersistTaps?:string}){return <div style={{overflow:'auto',flex:horizontal?'0 0 auto':1,minHeight:0,...flatten(style)}}><View style={{flexDirection:horizontal?'row':'column',...flatten(contentContainerStyle)}}>{children}</View></div>;}
export function Pressable({children,style,onPress,accessibilityState,accessibilityLabel}:Box&{onPress:()=>unknown;accessibilityState?:{selected?:boolean}}){return <button className="pressable" aria-label={accessibilityLabel} aria-pressed={accessibilityState?.selected} onClick={()=>void onPress()} style={{...flatten(style)}}>{children}</button>;}
export function Texte({children,variante,couleur,style,accessibilityRole}:Box&{variante?:string;couleur?:string}){return <span role={accessibilityRole} className={`text ${variante||'corps'}`} style={{color:couleur,...flatten(style)}}>{children}</span>;}
export function Bouton({titre,onPress,ton='action',taille,desactive}: {titre:string;onPress?:()=>unknown;ton?:string;taille?:string;desactive?:boolean}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');const lock=useRef(false);return <><button className={`button ${ton} ${taille||''}`} disabled={desactive||busy} onClick={async()=>{if(lock.current||!onPress)return;lock.current=true;setError('');setBusy(true);try{await onPress();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}}>{busy?'En cours…':titre}</button>{error&&<span role="alert" style={{color:colors.danger,fontSize:13}}>{error}</span>}</>;}
export function Champ({label,value,onChangeText,placeholder,multiline,style,suffixe,accessibilityLabel,keyboardType}: {label?:string;value:string;onChangeText:(s:string)=>void;placeholder?:string;multiline?:boolean;style?:Style;suffixe?:string;accessibilityLabel?:string;keyboardType?:string}){return <label className="field" style={flatten(style)}>{label&&<span>{label}</span>}<div>{multiline?<textarea value={value} onChange={e=>onChangeText(e.target.value)} placeholder={placeholder} aria-label={accessibilityLabel||label}/>:<input value={value} onChange={e=>onChangeText(e.target.value)} placeholder={placeholder} aria-label={accessibilityLabel||label} inputMode={keyboardType==='decimal-pad'?'decimal':undefined}/>} {suffixe&&<span>{suffixe}</span>}</div></label>;}
export function Etiquette({libelle,ton}: {libelle:string;ton?:string}){return <span className={`badge ${ton||'neutre'}`}>{libelle}</span>;}
export function Switch({value,onValueChange,accessibilityLabel}: {value:boolean;onValueChange:(v:boolean)=>void;accessibilityLabel:string;trackColor?:unknown}){return <button className={`switch ${value?'on':''}`} role="switch" aria-checked={value} aria-label={accessibilityLabel} onClick={()=>onValueChange(!value)}><span/></button>;}
export function ActivityIndicator({color}: {color?:string}){return <div className="spinner" role="status" aria-label="Chargement" style={{borderTopColor:color}}/>;}
export function Logotype({hauteur=32,sombre=false}:{hauteur?:number;sombre?:boolean}){return <svg width={hauteur*3.1} height={hauteur} viewBox="0 0 124 40" role="img" aria-label="Liked"><g stroke={sombre?'white':colors.encre} strokeWidth="5" strokeLinecap="round" fill="none"><path d="M8 6v26M26 18v14M44 6v26M44 24l12-10M46.5 22.5L58 32"/><circle cx="78" cy="25" r="7.5"/><path d="M85.5 25h-15"/><circle cx="106" cy="25" r="7.5"/><path d="M113.5 6v26"/></g><path d="M26 13s-8-5-8-9c0-5 6-5 8-1 2-4 8-4 8 1 0 4-8 9-8 9" fill={colors.corail}/></svg>;}
const icons:Record<string,string>={'grid-outline':'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z','pricetags-outline':'M3 3h8l10 10-8 8L3 11zM7 7h.01','people-outline':'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M18 8a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-4M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0','bag-handle-outline':'M4 7h16l1 14H3zM8 7V5a4 4 0 0 1 8 0v2','cube-outline':'M12 2l10 5v10l-10 5L2 17V7zM2 7l10 5 10-5M12 12v10','chatbubbles-outline':'M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4','flag-outline':'M4 22V2M4 3h8l2 2h7v11h-7l-2-2H4','flash-outline':'M13 2L3 14h8l-1 8 11-12h-8z','mail-outline':'M3 5h18v14H3zM3 5l9 8 9-8','download-outline':'M12 3v12M7 10l5 5 5-5M3 16v5h18v-5','options-outline':'M4 5h16M4 12h16M4 19h16M8 2v6M16 9v6M9 16v6','list-outline':'M8 5h13M8 12h13M8 19h13M3 5h.01M3 12h.01M3 19h.01','leaf-outline':'M20 3c-20 0-20 18-7 18 9 0 8-9 7-18M3 22L17 8'};
export function Ionicons({name,size=20,color}:{name:string;size?:number;color?:string}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color||'currentColor'} strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={icons[name]||icons['grid-outline']}/></svg>;}
export const Platform={OS:'web'};
export const StyleSheet={create:<T extends Record<string,CSSProperties>>(styles:T)=>styles};
export function useWindowDimensions(){const [width,setWidth]=useState(window.innerWidth);useEffect(()=>{const cb=()=>setWidth(window.innerWidth);window.addEventListener('resize',cb);return()=>window.removeEventListener('resize',cb);},[]);return {width};}
